FROM nginx:alpine
# Altera a porta padrão do Nginx de 80 para 3000
RUN sed -i 's/listen \(.*\)80;/listen 3000;/g' /etc/nginx/conf.d/default.conf
# Copia todos os arquivos do seu frontend para a pasta do servidor
COPY . /usr/share/nginx/html/

EXPOSE 3000